// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwTAF5qbgZ58vxxeSOHwFt2Nuae7CQClU',
    appId: '1:699539110146:web:842e6a334aa3de9f9c2a1b',
    messagingSenderId: '699539110146',
    projectId: 'stores-app-ba8c6',
    authDomain: 'stores-app-ba8c6.firebaseapp.com',
    storageBucket: 'stores-app-ba8c6.firebasestorage.app',
    measurementId: 'G-JT1T3KJXED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXuLDvJ5FxisC8T3UdQ8pq5e3fqKdNxI',
    appId: '1:699539110146:android:baf78d18dfd1354f9c2a1b',
    messagingSenderId: '699539110146',
    projectId: 'stores-app-ba8c6',
    storageBucket: 'stores-app-ba8c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdpB7Zk4DdB-EHrn3WFLiX3DdLfzdnrDU',
    appId: '1:699539110146:ios:6f3b3e864237a3719c2a1b',
    messagingSenderId: '699539110146',
    projectId: 'stores-app-ba8c6',
    storageBucket: 'stores-app-ba8c6.firebasestorage.app',
    iosBundleId: 'com.example.fcaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdpB7Zk4DdB-EHrn3WFLiX3DdLfzdnrDU',
    appId: '1:699539110146:ios:6f3b3e864237a3719c2a1b',
    messagingSenderId: '699539110146',
    projectId: 'stores-app-ba8c6',
    storageBucket: 'stores-app-ba8c6.firebasestorage.app',
    iosBundleId: 'com.example.fcaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwTAF5qbgZ58vxxeSOHwFt2Nuae7CQClU',
    appId: '1:699539110146:web:1bf0226bf29805879c2a1b',
    messagingSenderId: '699539110146',
    projectId: 'stores-app-ba8c6',
    authDomain: 'stores-app-ba8c6.firebaseapp.com',
    storageBucket: 'stores-app-ba8c6.firebasestorage.app',
    measurementId: 'G-XS4WGQ5WW3',
  );
}
